management:
  endpoints:
    web:
      exposure:
        include: '*'
hystrix:
  stream:
    queue:
      enabled: false
  command:
    default:
      execution:
        isolation:
          thread:
            timeoutInMilliseconds: 12000
