management:
  endpoints:
    web:
      exposure:
        include: '*'
hystrix:
  stream:
    queue:
      enabled: ${PIVOTAL_DASHBOARD_ENABLED:false}
  command:
    default:
      execution:
        isolation:
          thread:
            timeoutInMilliseconds: 30000
